---
apiVersion: v1
kind: Secret
metadata:
  name: argo-cd-cluster-core
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "core"
  server: "https://kubernetes.default.svc"
  config: |
    {}

---
apiVersion: v1
kind: Secret
metadata:
  name: argo-cd-cluster-prod
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "prod"
  server: "https://kubernetes.default.svc"
  config: |
    {}

---
apiVersion: v1
kind: Secret
metadata:
  name: argo-cd-cluster-staging
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "staging"
  server: "https://kubernetes.default.svc"
  config: |
    {}
