apiVersion: v2
appVersion: "1.0"
description: A Helm chart for ShopEntrance ArgoCD
name: argo-cd
version: 1.0.0

dependencies:
  - name: argo-cd
    version: v5.51.5
    repository: https://argoproj.github.io/argo-helm
